### ISSUE TITLE
Signature not matched with java signature

### ISSUE THREAD

**Issue by VishnuGShephertz** [adafruit/Adafruit-Tweet-Receipt#6]
My java code signature is not matched with the signature of Arduino . My code is below.
Java signature
B4Nb2uSQUQvSbfi6tM6oJMusGRY= Java signature
QaZBHQe+W1qFHE7tVFj10XC02eU= Arduino Signature

**Comment by ladyada** [comment]
hiya this repo is being archived and moreover will not work with twitter anymore so closing all issues
